stages:
- prepare
- prebuild
- test
- coverage
- build
- integration
- package
- static QA
- build release artifacts
- trigger release
- docs

include:
- local: /.gitlab/ci/_common.gitlab-ci.yml
- local: /.gitlab/ci/_rules.gitlab-ci.yml
- local: /.gitlab/ci/prepare.gitlab-ci.yml
- local: /.gitlab/ci/prebuild.gitlab-ci.yml
- local: /.gitlab/ci/test.gitlab-ci.yml
- local: /.gitlab/ci/coverage.gitlab-ci.yml
- local: /.gitlab/ci/build.gitlab-ci.yml
- local: /.gitlab/ci/integration.gitlab-ci.yml
- local: /.gitlab/ci/package.gitlab-ci.yml
- local: /.gitlab/ci/static-qa.gitlab-ci.yml
- local: /.gitlab/ci/build-release-artifacts.yml
- local: /.gitlab/ci/trigger-release.gitlab-ci.yml
- local: /.gitlab/ci/docs.gitlab-ci.yml
