.dotjob:
  variables:
    FILE_REF: $FILE_VAR
  script:
    - echo FILE_VAR=$FILE_VAR
    - echo FILE_REF=$FILE_REF

run_on_linux:
  extends: .dotjob

run_on_macos:
  extends: .dotjob
  image: macos-12-xcode-13
  tags:
    - shared-macos-amd64
