stages:
- scan
- prepare
- prebuild
- test
- coverage
- build
- package
- release
- docs

include:
- template: Dependency-Scanning.gitlab-ci.yml
- local: /.gitlab/ci/_common.gitlab-ci.yml
- local: /.gitlab/ci/prepare.gitlab-ci.yml
- local: /.gitlab/ci/prebuild.gitlab-ci.yml
- local: /.gitlab/ci/test.gitlab-ci.yml
- local: /.gitlab/ci/coverage.gitlab-ci.yml
- local: /.gitlab/ci/build.gitlab-ci.yml
- local: /.gitlab/ci/package.gitlab-ci.yml
- local: /.gitlab/ci/release.gitlab-ci.yml
- local: /.gitlab/ci/docs.gitlab-ci.yml

dependency_scanning:
  stage: scan

