stages:
- prepare
- fips helper binaries
- prebuild #need
- prerelease # need
- test # need
- coverage # need
- build
- package
- release
- postrelease
- docs

include:
- local: /.gitlab/ci/_common.gitlab-ci.yml
- local: /.gitlab/ci/_rules.gitlab-ci.yml
- local: /.gitlab/ci/prepare.gitlab-ci.yml
- local: /.gitlab/ci/fips-helper-binaries.gitlab-ci.yml
- local: /.gitlab/ci/prebuild.gitlab-ci.yml
- local: /.gitlab/ci/prerelease.gitlab-ci.yml
- local: /.gitlab/ci/test.gitlab-ci.yml
- local: /.gitlab/ci/coverage.gitlab-ci.yml
