run:
  concurrency: 8
  deadline: 1m
  issues-exit-code: 1
  modules-download-mode: vendor
  tests: true
  skip-dirs:
    - vendor
    - .gopath
  skip-files:
    - mock_*.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  govet:
    check-shadowing: false

linters:
  disable-all: true
  enable:
    - gocyclo
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - structcheck
    - varcheck
  fast: false

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: helpers/shell_escape.go
      linters:
        - gocyclo
    - path: helpers/shell/legacy_expand.go
      linters:
        - gocyclo
    - path: executors/kubernetes/kubernetes_test.go
      linters:
        - gocyclo
    - path: executors/kubernetes/util_test.go
      linters:
        - gocyclo
    - path: executors/kubernetes/exec_test.go
      linters:
        - gocyclo
    - path: executors/parallels/
      linters:
        - gocyclo
    - path: executors/virtualbox/
      linters:
        - gocyclo
    - linters:
        - golint
      text: "don't use ALL_CAPS in Go names; use CamelCase"
    - linters:
        - golint
      text: "don't use an underscore in package name"
