run:
  concurrency: 8
  deadline: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - mock_*.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: false
  goconst:
    min-len: 3
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - goconst
    - gocyclo
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - whitespace
  fast: false

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - text: "don't use ALL_CAPS in Go names; use CamelCase"
      linters:
        - golint
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - path: ".*_test.go"
      linters:
        - bodyclose
        - goconst
