---
# Extended Markdown configuration to enforce no-trailing-spaces rule
# To use this configuration, in the project directory run:
#   cd docs
#   markdownlint-cli2 --config .markdownlint/.markdownlint-cli2.yaml '**/*.md'

fix: true
config:
  default: false
  no-trailing-spaces: true
