##############
# Conditions #
##############

.if-not-canonical-namespace: &if-not-canonical-namespace
  if: '$CI_PROJECT_NAMESPACE !~ /^gitlab-org($|\/)/'

.if-default-branch: &if-default-branch
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-release-candidate: &if-release-candidate
  if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+/'

.if-stable-release: &if-stable-release
  if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

.if-docs-branch: &if-docs-branch
  if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /(^docs[\/-].*|.*-docs$)/

.if-merge-request-pipeline: &if-merge-request-pipeline
  if: $CI_PIPELINE_SOURCE == "merge_request_event"

.if-runner-merge-request-pipeline: &if-runner-merge-request-pipeline
  if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH == "gitlab-org/gitlab-runner"

.if-runner-security-merge-request-pipeline: &if-runner-security-merge-request-pipeline
  if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH == "gitlab-org/security/gitlab-runner"

.if-runner-default-branch: &if-runner-default-branch
  if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH == "gitlab-org/gitlab-runner"

.if-runner-or-security-runner-default-branch: &if-runner-or-security-runner-default-branch
  if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PROJECT_PATH == "gitlab-org/gitlab-runner" || $CI_PROJECT_PATH == "gitlab-org/security/gitlab-runner")

.if-runner-or-security-runner-stable: &if-runner-or-security-runner-stable
  if: $CI_COMMIT_REF_NAME =~ /\A[0-9]+-[0-9]+-stable\z/ && ($CI_PROJECT_PATH == "gitlab-org/gitlab-runner" || $CI_PROJECT_PATH == "gitlab-org/security/gitlab-runner")

.if-runner-release: &if-runner-release
  if: $CI_COMMIT_REF_NAME =~ /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\z/ && $CI_PROJECT_PATH == "gitlab-org/gitlab-runner"

.if-runner-stable-release: &if-runner-stable-release
  if: $CI_COMMIT_REF_NAME =~ /\Av[0-9]+\.[0-9]+\.[0-9]+?\z/ && $CI_PROJECT_PATH == "gitlab-org/gitlab-runner"

.if-security-runner-release: &if-security-runner-release
  if: $CI_COMMIT_REF_NAME =~ /\Av[0-9]+\.[0-9]+\.[0-9]+?\z/ && $CI_PROJECT_PATH == "gitlab-org/security/gitlab-runner"

.if-runner-bleeding-edge-release: &if-runner-bleeding-edge-release
  if: $CI_COMMIT_REF_NAME =~ /\Av[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+\z/ && $CI_PROJECT_PATH == "gitlab-org/gitlab-runner"

########################
# Default branch rules #
########################

.rules:default-branch-only:
  rules:
  - <<: *if-runner-or-security-runner-default-branch

.rules:default-branch-only:always:
  rules:
  - <<: *if-runner-or-security-runner-default-branch
    when: always

#######################
# Merge Request rules #
#######################

.rules:merge_request_pipelines:
  rules:
  - <<: *if-merge-request-pipeline
  - <<: *if-runner-or-security-runner-default-branch
  - <<: *if-runner-or-security-runner-stable
  - <<: *if-runner-release
  - <<: *if-security-runner-release

.rules:merge_request_pipelines:no_docs:
  rules:
  - <<: *if-docs-branch
    when: never
  - <<: *if-merge-request-pipeline
  - <<: *if-runner-or-security-runner-default-branch
  - <<: *if-runner-or-security-runner-stable
  - <<: *if-runner-release
  - <<: *if-security-runner-release

.rules:merge_request_pipelines:no_docs:always:
  rules:
  - <<: *if-docs-branch
    when: never
  - <<: *if-merge-request-pipeline
    when: always
  - <<: *if-runner-or-security-runner-default-branch
    when: always
  - <<: *if-runner-or-security-runner-stable
    when: always
  - <<: *if-runner-release
    when: always
  - <<: *if-security-runner-release
    when: always

#################
# Release rules #
#################

.rules:release:all:
  rules:
  - <<: *if-not-canonical-namespace
    when: never
  - <<: *if-default-branch
  - <<: *if-release-candidate
  - <<: *if-stable-release

.rules:release:bleeding-edge:
  rules:
  - <<: *if-docs-branch
    when: never
  - <<: *if-runner-default-branch
  - <<: *if-runner-bleeding-edge-release

.rules:release:stable:
  rules:
  - <<: *if-docs-branch
    when: never
  - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_PATH == "gitlab-org/gitlab-runner"
    when: on_success
  - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_PATH == "gitlab-org/security/gitlab-runner"
    when: manual

.rules:release:stable:branch:
  rules:
  - <<: *if-docs-branch
    when: never
  - <<: *if-runner-stable-release
  - <<: *if-security-runner-release

.rules:release:development:merge-requests:
  rules:
  - <<: *if-docs-branch
    when: never
  - <<: *if-runner-merge-request-pipeline
  - <<: *if-runner-security-merge-request-pipeline

.rules:runner-only:release:development:merge-requests:
  rules:
  - <<: *if-docs-branch
    when: never
  - <<: *if-runner-merge-request-pipeline

##############
# Docs rules #
##############

.rules:docs:skip:
  rules:
  - <<: *if-docs-branch
    when: never
  - when: on_success

.rules:docs:review:
  rules:
  - <<: *if-not-canonical-namespace
    when: never
  - <<: *if-merge-request-pipeline
    when: manual
