build runner images:
  stage: build runner images
  extends:
  - .docker
  - .docker_qemu
  - .linux-dependency-checksums
  - .rules:merge_request_pipelines:no_docs
  dependencies:
  - 'binaries'
  - 'package-deb'
  - 'binaries-fips'
  - 'package-rpm: [package-rpm-fips]'
  script:
  - make build_docker_images
  artifacts:
    paths:
    - out/runner-images
    expire_in: 7d
  parallel:
    matrix:
    - IMAGE_FLAVOR: ubi-fips
      TARGET_ARCH: amd64
    - IMAGE_FLAVOR: ubuntu
      TARGET_ARCH:
      - amd64
      - arm64
      - ppc64le
      - s390x
    - IMAGE_FLAVOR: alpine3.12
      TARGET_ARCH:
      - amd64
      - arm64
      - ppc64le
      - s390x
    - IMAGE_FLAVOR: alpine3.13
      TARGET_ARCH:
      - amd64
      - arm64
      - ppc64le
      - s390x
    - IMAGE_FLAVOR: alpine3.14
      TARGET_ARCH:
      - amd64
      - arm64
      - ppc64le
      - s390x
    - IMAGE_FLAVOR: alpine3.15
      TARGET_ARCH:
      - amd64
      - arm64
      - ppc64le
      - s390x

