trigger UBI images build:
  stage: postrelease
  extends:
  - .rules:release:stable:branch
  - .rules:release:bleeding-edge
  variables:
    BUILD_RELEASE: ${CI_COMMIT_REF_NAME}
  trigger: gitlab-org/ci-cd/gitlab-runner-ubi-images
