helper images:
  extends:
  - .docker
  - .go-cache-docker-qemu
  stage: prebuild
  script:
  - make helper-bin BINARIES="out/binaries/gitlab-runner-helper/gitlab-runner-helper.x86_64" helper-dockerarchive TAR_XZ="out/helper-images/prebuilt-x86_64.tar.xz"
  retry: 2
  artifacts:
    paths:
    - out/helper-images/
    - out/binaries/gitlab-runner-helper/gitlab-runner-helper*
    - .gopath/bin
    - .gopath/.ok
    expire_in: 7d

#clone test repo:
#  extends:
#  - .merge_request_pipelines
#  - .except_docs
#  - .no_cache_and_dependencies
#  stage: prebuild
#  variables:
#    GIT_STRATEGY: none
#  script:
#  - mkdir tmp
#  - succeed=0
#  - for i in {1..3}; do git clone https://gitlab.com/gitlab-org/ci-cd/tests/gitlab-test.git tmp/gitlab-test && succeed=1 && break; echo "retrying"; done
#  - '[[ "$succeed" -eq 1 ]]'
#  artifacts:
#    paths:
#    - tmp/gitlab-test
#    expire_in: 7d
#
#tests definitions:
#  extends:
#  - .merge_request_pipelines
#  - .except_docs
#  - .go-cache
#  stage: prebuild
#  script:
#  - apt-get update
#  - apt-get install -y make
#  - source ci/touch_make_dependencies
#  - make parallel_test_prepare
#  artifacts:
#    paths:
#    - testsdefinitions.txt
#    expire_in: 7d
#
## prepare done is used as a sentinel for "Prepare" stage completion, so we can kick off builds in later stages
## without waiting for the completion of the Prebuild stage
#prepare done:
#  stage: prebuild
#  extends:
#  - .stage_done
