helper images:
  extends:
  - .merge_request_pipelines
  - .docker
  #- .go-cache-docker-qemu
  stage: prebuild
  image: golang:1.13.8-alpine
  script:
  - apk add --no-cache bash make git wget xz
  - wget -q https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz -O /tmp/docker.tar.gz &&
    tar -xzf /tmp/docker.tar.gz -C /tmp/ &&
    cp /tmp/docker/docker* /usr/bin &&
    chmod +x /usr/bin/docker* &&
    rm -rf /tmp/*
  - mkdir -p ~/.docker/cli-plugins &&
    wget -q https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx &&
    chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - make helper-bin helper-dockerarchive
  retry: 2
  artifacts:
    paths:
    - out/helper-images/
    - out/binaries/gitlab-runner-helper/gitlab-runner-helper*
    - .gopath/bin
    - .gopath/.ok
    expire_in: 7d

clone test repo:
  extends:
  - .merge_request_pipelines
  - .except_docs
  - .no_cache_and_dependencies
  stage: prebuild
  variables:
    GIT_STRATEGY: none
  script:
  - mkdir tmp
  - succeed=0
  - for i in {1..3}; do git clone https://gitlab.com/gitlab-org/ci-cd/tests/gitlab-test.git tmp/gitlab-test && succeed=1 && break; echo "retrying"; done
  - '[[ "$succeed" -eq 1 ]]'
  artifacts:
    paths:
    - tmp/gitlab-test
    expire_in: 7d

tests definitions:
  extends:
  - .merge_request_pipelines
  - .except_docs
  - .go-cache
  stage: prebuild
  script:
  - apt-get update
  - apt-get install -y make
  - source ci/touch_make_dependencies
  - make parallel_test_prepare
  artifacts:
    paths:
    - testsdefinitions.txt
    expire_in: 7d

# prepare done is used as a sentinel for "Prepare" stage completion, so we can kick off builds in later stages
# without waiting for the completion of the Prebuild stage
prepare done:
  stage: prebuild
  extends:
  - .stage_done
