.image_builder:
  extends:
  - .docker
  stage: prepare
  image: docker:${DOCKER_VERSION}-git
  script:
  - source ./ci/build_ci_image
  only:
    refs:
    - merge_requests@gitlab-org/gitlab-runner

prepare ci image:
  extends:
  - .image_builder
  - .linux-dependency-checksums
  variables:
    GO_VERSION: 1.13.8
    GO_LINUX_AMD64_CHECKSUM: "0567734d558aef19112f2b2873caa0c600f1b4a5827930eb5a7f35235219e9d8"
  script:
    - BUILD_DOCKERFILE=./dockerfiles/ci/Dockerfile.tests BUILD_IMAGE=${CI_IMAGE} source ./ci/build_ci_image
    - BUILD_DOCKERFILE=./dockerfiles/ci/Dockerfile.packaging BASE_IMAGE=${CI_IMAGE} BUILD_IMAGE=${CI_IMAGE}-packaging source ./ci/build_ci_image
  only:
    changes:
    - dockerfiles/ci/*
    - .gitlab/ci/_common.gitlab-ci.yml
    - .gitlab/ci/prepare.gitlab-ci.yml

prepare alpine-no-root image:
  extends:
  - .image_builder
  variables:
    BUILD_IMAGE: registry.gitlab.com/gitlab-org/gitlab-runner/alpine-no-root:latest
    BUILD_DOCKERFILE: ./tests/dockerfiles/alpine-no-root/Dockerfile
  only:
    changes:
    - tests/dockerfiles/alpine-no-root/*
    - .gitlab/ci/prepare.gitlab-ci.yml
