.image_builder:
  extends:
  - .docker
  - .rules:image_builder
  stage: prepare
  image: docker:${DOCKER_VERSION}-git
  script:
  - source ./ci/build_ci_image

prepare ci image:
  extends:
  - .image_builder
  - .rules:prepare_ci_image
  variables:
    BUILD_IMAGE: $CI_IMAGE
    BUILD_DOCKERFILE: ./dockerfiles/ci/Dockerfile
    GIT_LFS_256_CHECKSUM: 46508eb932c2ec0003a940f179246708d4ddc2fec439dcacbf20ff9e98b957c9

prepare alpine-no-root image:
  extends:
  - .image_builder
  - .rules:prepare_alpine-no-root_image
  variables:
    BUILD_IMAGE: registry.gitlab.com/gitlab-org/gitlab-runner/alpine-no-root:latest
    BUILD_DOCKERFILE: ./tests/dockerfiles/alpine-no-root/Dockerfile
