.release_docker_images:
  extends:
  - .docker
  stage: release
  variables:
    PUBLISH_IMAGES: "true"
    PUSH_TO_DOCKER_HUB: "true"
    TARGET_ARCHS: "amd64,arm64"
    DOCKER_MACHINE_AMD64_CHECKSUM: "a7f7cbb842752b12123c5a5447d8039bf8dccf62ec2328853583e68eb4ffb097"
    DOCKER_MACHINE_ARM64_CHECKSUM: "109f534bfb8b9b852c938cad978e60a86b13f5ecf92da5e24320dacd2a7216ac"
    DUMB_INIT_AMD64_CHECKSUM: "37f2c1f0372a45554f1b89924fbb134fc24c3756efaedf11e07f599494e0eff9"
    DUMB_INIT_ARM64_CHECKSUM: "45b1bbf56cc03edda81e4220535a025bfe3ed6e93562222b9be4471005b3eeb3"
    GIT_LFS_AMD64_CHECKSUM: "c8952ee72af214e3669f834d829e8a0a3becd160dead18237f99e40d75a3e920"
    GIT_LFS_ARM64_CHECKSUM: "7a80464be13acc23ac99fd33e4b4352894f0fe3a8794b270e964c9532941834d"
  needs:
  - 'helper images'
  - 'binaries linux/386 linux/amd64 linux/arm linux/arm64'
  - 'package-deb'
  script:
  - source ci/touch_make_dependencies
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - make release_docker_images


.release:
  extends:
  - .except_docs
  stage: release
  before_script:
  - unset GPG_KEY
  - source ci/touch_make_dependencies


.release_packagecloud:
  needs:
  - 'package-deb'
  - 'package-rpm'
  extends:
  - .release
  script:
  - make release_packagecloud

.release_development:
  only:
  - merge_requests@gitlab-org/gitlab-runner
  except:
    variables:
    - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /(^docs[\/-].*|.*-docs$)/

.release_bleeding_edge:
  only:
  - master@gitlab-org/gitlab-runner
  - /\Av[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+\Z/@gitlab-org/gitlab-runner

.release_stable:
  only:
  - /\Av[0-9]+\.[0-9]+\.[0-9]+\Z/@gitlab-org/gitlab-runner


development docker images:
  extends:
  - .release_docker_images
  - .release_development
  variables:
    PUBLISH_IMAGES: "false"
    PUSH_TO_DOCKER_HUB: "false"


bleeding edge packagecloud:
  extends:
  - .release_packagecloud
  - .release_bleeding_edge
  environment:
    name: bleeding_edge/packagecloud
    url: https://packages.gitlab.com/runner/unstable

bleeding edge docker images:
  extends:
  - .release_docker_images
  - .release_bleeding_edge
  environment:
    name: bleeding_edge/docker_images
    url: https://hub.docker.com/r/gitlab/gitlab-runner/tags/


stable packagecloud:
  extends:
  - .release_packagecloud
  - .release_stable
  environment:
    name: stable/packagecloud
    url: https://packages.gitlab.com/runner/gitlab-runner

stable docker images:
  extends:
  - .release_docker_images
  - .release_stable
  environment:
    name: stable/docker_images
    url: https://hub.docker.com/r/gitlab/gitlab-runner/tags/

