code_quality:
  stage: test
  image: golangci/golangci-lint:v1.24.0
  variables:
    REPORT_FILE: gl-code-quality-report.json
    LINT_FLAGS: "--issues-exit-code 0 --color never --deadline 15m"
    ADDITIONAL_LINTERS: "" # Turn off additional linters since they cause a hang
    OUT_FORMAT: code-climate
    GOGC: 100
  script:
  - make lint | tee ${REPORT_FILE}
  timeout: 20 minutes
  artifacts:
    reports:
      codequality: ${REPORT_FILE}
    paths:
    - ${REPORT_FILE}
    expire_in: 7d

